### Numpy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [3]:
import numpy as np

## Create an array using numpy
# create 1D array
lst = [1,2,3,4,5,6]
arr1=np.array(lst)
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
print(arr1.shape)
print(arr1.reshape(1,6))
print(arr1.reshape(2,3))
print(arr1.reshape(3,2))

(6,)
[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [5]:
arr2 = np.array(lst)
print(arr2.reshape(3,2))
print(arr2.reshape(6,1).shape)

[[1 2]
 [3 4]
 [5 6]]
(6, 1)


In [6]:
# 2D array
arr2=np.array([[1,2,3,4],[3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4]
 [3 4 5 6]]
(2, 4)


In [7]:
np.arange(0,11,2).reshape(6,1)

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((3,6))


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
## Attributes of numpy
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size (number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes)",arr.itemsize)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes) 8


In [12]:
## Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([10,20,30,40,50,60])

## Addition
print("Addition:",arr1+arr2)

## Substraction
print("Substraction:",arr1-arr2)

## Multiplication
print("Multiplication:",arr1*arr2)

## Division
print("Division:",arr1/arr2)



Addition: [11 22 33 44 55 66]
Substraction: [ -9 -18 -27 -36 -45 -54]
Multiplication: [ 10  40  90 160 250 360]
Division: [0.1 0.1 0.1 0.1 0.1 0.1]


In [13]:
print(np.sqrt(arr2))
print(np.mean(arr2))
print(np.median(arr2))
print(np.sin(arr2))
print(np.exp(arr1))
print(np.max(arr2))
print(np.min(arr1))
print(np.tan(arr2))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669]
35.0
35.0
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485 -0.30481062]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
60
1
[ 0.64836083  2.23716094 -6.4053312  -1.11721493 -0.27190061  0.32004039]


In [14]:
###  Array Sclicing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print(arr[0][0])
print(arr[0:2:,2:])


1
[[3 4]
 [7 8]]


In [16]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [17]:
print(arr[1:,2:])


[[ 7  8]
 [11 12]]


In [18]:
### MOdify array elements
arr[0][0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [19]:
arr[1:] = 100

In [20]:
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [21]:
## Statistical Concepts -- Normalization
## to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5,6])

# calculate the mean and std deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean)/std_dev
print("Normalized data:",normalized_data)





Normalized data: [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


In [22]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print(f"Mean: {mean}")

#Median
median = np.median(data)
print(f"Median: {median}")

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:",std_dev)

#Variance
variance = np.var(data)
print("Variance:",variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [23]:
## Logical Operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

print(data[data>5])
print(data[data<7])
print(data[(data >3) & (data<8)])


[ 6  7  8  9 10]
[1 2 3 4 5 6]
[4 5 6 7]


In [ ]:
a = np.arange(6)
print(a)
print(type(a))
for x in np.nditer(a):
    print(x)

[0 1 2 3 4 5]
<class 'numpy.ndarray'>
0
1
2
3
4
5
